### ISSUE TITLE
Setup use cancer use case

### ISSUE THREAD

**Issue by holtgrewe** [bihealth/snappy-pipeline#1]
https://github.com/bihealth/snappy-use-case-cancer

Germline as  the template:

https://github.com/bihealth/snappy-use-case-germline/

**Comment by holtgrewe** [comment]
Minimal work here, follow-up in #9.

**Comment by mbenary** [comment]
Ok, I added the first files in the project - are they enough to close this issue?

**Comment by holtgrewe** [comment]
lgtm
