### ISSUE TITLE
Base recalibration in ngs_mapping

### ISSUE THREAD

**Issue by ericblanc20** [bihealth/snappy-pipeline#187]
**Is your feature request related to a problem? Please describe.**
Base recalibration is part of the GATK best practices for somatic variant calling.

**Describe the solution you'd like**
Base recalibration should be optionally provided by the `ngs_mapping` step.

**Describe alternatives you've considered**
A separate step for base recalibration. However, it doubles the amount of large files stored during processing, it causes some uncertainty as which bam should be uploaded to SODAR, and it doesn't offer additional features.

**Additional context**

**Comment by eudesbarbosa** [comment]
@ericblanc20, can you please share a link to the protocol you based the ticket on? 

Regarding the different BAM files, if all are necessary we could simply add the new files to `ngs_mapping/output/{mapper}.{library_name}` and that should be enough - `cubi-tk snappy itransfer-ngs-mapping` is based on directories, not files.

**Comment by ericblanc20** [comment]
I didn't make my homework: `ngs_mapping` already provides base recalibration, no need to do anything.

However, the base recalibration is currently done using GATK non free. There is a free version since January 2018. We should move to GATK4 eventually. The topic is discussed in [issure 191: GATK4](https://github.com/bihealth/snappy-pipeline/issues/191).
