### ISSUE TITLE
Add second placeholder/tag besides REQUIRED in config defaults

### ISSUE THREAD

**Issue by holtgrewe** [bihealth/snappy-pipeline#196]
...on second thought, they are not really required. Perhaps we should consider including other tags, not only `REQUIRED`.

_Originally posted by @eudesbarbosa in https://github.com/bihealth/snappy-pipeline/pull/195#discussion_r963594843_

**Comment by eudesbarbosa** [comment]
I suggest `OPTIONAL` as it is already used in several workflows:

- snappy-pipeline/snappy_pipeline/workflows/somatic_ngs_sanity_checking/__init__.py
- snappy-pipeline/snappy_pipeline/workflows/variant_annotation/__init__.py
- snappy-pipeline/snappy_pipeline/workflows/somatic_variant_filtration/__init__.py
- snappy-pipeline/snappy_pipeline/workflows/ngs_sanity_checking/__init__.py
- snappy-pipeline/snappy_pipeline/workflows/somatic_hla_loh_calling/__init__.py
- snappy-pipeline/snappy_pipeline/workflows/somatic_gene_fusion_calling/__init__.py
- snappy-pipeline/snappy_pipeline/workflows/somatic_wgs_sv_calling/__init__.py
- snappy-pipeline/snappy_pipeline/workflows/abstract/__init__.py
- snappy-pipeline/snappy_pipeline/workflows/variant_denovo_filtration/__init__.py
- snappy-pipeline/snappy_pipeline/workflows/cbioportal_export/__init__.py
- snappy-pipeline/snappy_pipeline/workflows/ngs_mapping/__init__.py
- snappy-pipeline/snappy_pipeline/workflows/variant_checking/__init__.py
- snappy-pipeline/snappy_pipeline/workflows/wgs_sv_calling/__init__.py
