### ISSUE TITLE
Allow targeted seq cnv calling with different kits

### ISSUE THREAD

**Issue by holtgrewe** [bihealth/snappy-pipeline#292]
**Is your feature request related to a problem? Please describe.**
We currently cannot run targeted seq cnv calling with different kits in one family.

**Describe the solution you'd like**
Re-use the old cnv/sv merging tool do this.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by xiamaz** [comment]
@holtgrewe Any specific project, where this is an issue right now?

**Comment by holtgrewe** [comment]
@xiamaz in our largest exome study
