### ISSUE TITLE
Class defined twice in file

### ISSUE THREAD

**Issue by eudesbarbosa** [bihealth/snappy-pipeline#41]
**Bug description:** 
Class `SomaticWgsSvCallingWorkflow` defined twice in `snappy_pipeline/workflows/somatic_wgs_sv_calling/__init__.py`.
Rename or remove one of the classes.

**Additional info:**
Codacy issue: https://app.codacy.com/gh/bihealth/snappy-pipeline/file/54235663449/issues/source?bid=22498844&fileBranchId=22498844#l378

**Comment by holtgrewe** [comment]
The first instance should be renamed to `SomaticWgsSvCallingStepPart` and then `MantaStep` should inherit from that.

**Comment by holtgrewe** [comment]
Can you do this?

**Comment by eudesbarbosa** [comment]
Sure :)

Just to confirm:
- [L-122](https://github.com/bihealth/snappy-pipeline/blob/master/snappy_pipeline/workflows/somatic_wgs_sv_calling/__init__.py#L112)  should be changed from `class SomaticWgsSvCallingWorkflow(BaseStep):` to `class SomaticWgsSvCallingStepPart (BaseStep):`
- [L-181](https://github.com/bihealth/snappy-pipeline/blob/master/snappy_pipeline/workflows/somatic_wgs_sv_calling/__init__.py#181) should be changed from `class MantaStepPart(SomaticWgsSvCallingWorkflow):` to `class MantaStepPart(SomaticWgsSvCallingStepPart):`
- [L-378](https://github.com/bihealth/snappy-pipeline/blob/master/snappy_pipeline/workflows/somatic_wgs_sv_calling/__init__.py#L378) remains the same: `class SomaticWgsSvCallingWorkflow(BaseStepPart):`

...correct?
