### ISSUE TITLE
Allowing wrappers to use singularity containers

### ISSUE THREAD

**Issue by ericblanc20** [bihealth/snappy-pipeline#445]
**Is your feature request related to a problem? Please describe.**
Some steps require very complex environments, with elements **not** available from conda environment repositories. For example:
- [PureCN](https://bioconductor.org/packages/release/bioc/html/PureCN.html) (used in `panel_of_normals` & `somatic_targeted_seq_cnv_calling`) requires [GenomicsDB](https://www.genomicsdb.org/)
- We may want to use [pvacseq](https://pvactools.readthedocs.io/en/latest/pvacseq.html) for neo-epitope predictions
- Other methods implemented in R provide docker containers rather the conda packages.

**Describe the solution you'd like**
A generic wrapper that could install a docker container in `work/containers`, in the same way that the `r/wrapper.py` installs packages from CRAN, Bioconductor, github or bitbucket.

**Describe alternatives you've considered**
We could create conda recipes for the missing packages.

**Additional context**
A docker image would be stored in the `work` directory of each project. It is wasteful in terms of disk usage, but not more than the current conda packages installed by snakemake. Especially when snakemake installs R & bioconductor packages.

**Comment by Nicolai-vKuegelgen** [comment]
I think that current snakemake versions can directly use (public) docker containers instead of conda enviroments for rule execution. I haven't tested this yet (though I want to soon, for other projects). I think if this works reliably it would circumvent having to install/provide all containers locally for each installation.

**Comment by ericblanc20** [comment]
Singularity containers are used in the somatic branch.

In the step `panel_of_normals`, action `install`, the `PureCN` container in installed in the `panel_of_normals/work/containers/out/<container name>.simg`.

Note that this particular container has multiple entry points: scripts to compute converage, to compute segmentations, ... Therefore, there is a need for a wrapper around the container (`snakemake` doesn't allow complex configuration of the run). An example is found in [PureCN's main wrapper](snappy_wrappers/wrappers/purecn/run/wrapper.py):

The paths for the vcf file, the panel of normals, ... must be made absolute, so that they can be passed (read-only) to the container. The container's mount points must also be created, and finally the actual command passed to the container must be created.

Ideally, these operations should be extracted from these particular wrappers, and put in generic tooling for the pipeline, to avoid cumbersome & error-prone boiler plate code duplication.
