### ISSUE TITLE
Add demultiplexing using UMIs

### ISSUE THREAD

**Issue by mbenary** [bihealth/snappy-pipeline#456]
**Is your feature request related to a problem? Please describe.**
Unique molecular identifiers (UMIs) are a type of molecular barcoding that provides error correction and increased accuracy during sequencing. DNA target enrichment library kits, like from Agilent Sure Select XT series, include molecular barcoding. This is especially of interest, when variants with low allele frequencies are to be detected.

**Describe the solution you'd like**
Include a new workflow for molecular demultiplexing. The preferred tool for the task is `umi-tools`, which provides the possibility to add an independent step after `ngs_mapping`. `umi-tools` is available via `bioconda`.

**Describe alternatives you've considered**
A second tool for molecular demultiplexing is `fgbio`, which is only available via github. Installation is done with [sbt](http://www.scala-sbt.org/). For me, it's not clear how to incorporate this in a wrapper for snappy.

**Comment by Nicolai-vKuegelgen** [comment]
Depending on how UMIs are designed `umi-tools` (but maybe also other tools) needs to be run both before and after ngs_mapping (the UMI sequence in the reads needs to be extracted and removed from the reads before mapping).

**Comment by ericblanc20** [comment]
This is currently addressed by the `somatic/mbcs` combo in `ngs_mapping`, but the current implementation has severe limitations:

- At the moment, the `mbcs` tool only deals with Agilent SureSelect XT barcodes (it uses the proprietary `AGeNT` software from Agilent, installed on the cluster). 
- Also, it cannot deal with files where the MBCs have been trimmed and put in the fastq title line's comment (as recent files from DKFZ). 
- We should really use free software, for example `umi-tools` as suggested by Nicolai.

Till wants to revise completely the `ngs_mapping` step, to break it into more manageable chunks, and use named pipes for efficiency. This will also be a good time to re-design the treatment of UMIs/MBCs, adatper trimming, post-processing such as Base Quality Score Recalibration (BQSR) and report (picard, test of relatedness, ...).
