### ISSUE TITLE
Chain of dependency issues when running somatic_variant_calling

### ISSUE THREAD

**Issue by mbenary** [bihealth/snappy-pipeline#488]
**Describe the bug**
When running a batch analysis for somatic variant calling, there is a chain of missing dependencies, namely:

- cffi
- numpy
- pandas

**To Reproduce**

1. Start a snappy-pipeline with a step for `somatic_variant_calling`
2. Start a batch analysis using slurm. It will fail with `cffi-error` (see #477)
3. Install `cffi` in the corresponding local environment
4. Start a batch analysis using slurm. It will fail  with the next dependency (see list above).
5. Install, rinse and repeat

**Comment by ericblanc20** [comment]
Fixed, see #477
