### ISSUE TITLE
Warning/error if no read mapper / variant caller is defined

### ISSUE THREAD

**Issue by holtgrewe** [bihealth/snappy-pipeline#49]
**Is your feature request related to a problem? Please describe.**
In the current `master`, if no read mappers for DNA/RNA are configured, no output file list is generated for Snakemake to process. This leads to confusion.

**Describe the solution you'd like**
Change the `ngs_mapping` step to check the sample sheet for DNA samples. If there is at least one then check if at least one dna read mapper is configured and output warning/error if this is not the case. Do the same for `dna_long` and `rna`.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by holtgrewe** [comment]
@eudesbarbosa what do you think?

**Comment by eudesbarbosa** [comment]
I think we should implement this with high prio. I fell for this issue twice already.

**Comment by eudesbarbosa** [comment]
I will need some help before I start digging too much into `biomedsheets`...

Is there any explicit `extractionType` in the sheets we are using?
How is this defined/extracted `library_name = donor.dna_ngs_library.name`?

```
[Custom Fields]
key     annotatedEntity docs    type    minimum maximum unit    choices pattern
batchNo bioEntity       Batch No.       integer .       .       .       .       .
familyId        bioEntity       Family  string  .       .       .       .       .
projectUuid     bioEntity       Project UUID    string  .       .       .       .       .
libraryKit      ngsLibrary      Enrichment kit  string  .       .       .       .       .

[Data]
familyId        patientName     fatherName      motherName      sex     isAffected      libraryType     folderName      batchNo hpoTerms        projectUuid     seqPlatform     libraryKit
```

**Comment by eudesbarbosa** [comment]
For future references, `DNA` is the default if `extractionType` is not defined:
https://biomedsheets.readthedocs.io/en/master/tsv_sheets.html#tsv-sheet-processing
