### ISSUE TITLE
Standardize imports

### ISSUE THREAD

**Issue by holtgrewe** [bihealth/snappy-pipeline#52]
**Is your feature request related to a problem? Please describe.**
Imports are a bit messy throughout the code base. We should standardize this and enforce it through Codacy or CI linting.

**Describe the solution you'd like**
Standardize towards the following:

- always use absolute imports
- go for google code order (see flake8-import-order below)
  - could be used for a checker [flake8-import-order](https://pypi.org/project/flake8-import-order/)
  - use [isort](https://pypi.org/project/isort/) to apply import order
- implement in Codacy as far as possible
- implement in CI if not possible in Codacy

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by eudesbarbosa** [comment]
So, `isort` seems to get the job done. It changed pretty much all of the files. A potential issue is that it doesn't play well with `black`. We can probably use both but there is a correct order. Example:
```
# isort
from biomedsheets.shortcuts import (donor_has_dna_ngs_library, write_pedigree_to_ped,
                                    write_pedigrees_to_ped)

# black
from biomedsheets.shortcuts import (
    donor_has_dna_ngs_library,
    write_pedigree_to_ped,
    write_pedigrees_to_ped,
)                                    
```

**Comment by eudesbarbosa** [comment]
...and of course, `flake8` also doesn't agree with `isort` =P

```
./snappy_pipeline/workflows/somatic_wgs_cnv_calling/__init__.py:78:1: I100 Import statements are in the wrong order. 'from collections import OrderedDict' should be before 'import sys'
```

**Comment by eudesbarbosa** [comment]
True, I was too quick to dismiss it. I'll get back to you later on.

**Comment by eudesbarbosa** [comment]
In the end, it wasn't so hard to find consensus. Draft in #53
